### ISSUE TITLE
question; how to fix `import Global.Unsafe (unsafeDecodeURI, unsafeEncodeURI)`

### ISSUE THREAD

**Issue by srghma** [purescript-contrib/purescript-js-uri#3]
```
[1/9 ModuleNotFound] .spago/halogen-storybook/master/src/Halogen/Storybook.purs:19:1

  19  import Global.Unsafe (unsafeDecodeURI, unsafeEncodeURI)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Module Global.Unsafe was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.
```

I cannot find these methods

**Comment by thomashoneyman** [comment]
If it's possible to use `decodeURIComponent` and `encodeURIComponent`, then you can get the unsafe version by calling `unsafePartial fromJust` on the result of decoding or encoding.

If `halogen-storybook` does require just `encodeURI` and `decodeURI`, then we can add those bindings to this library as well and I'd accept a PR for that. It would largely follow the pattern used for the existing definitions of `encodeURIComponent` and `decodeURIComponent`.

**Comment by srghma** [comment]
ok, tnx https://github.com/rnons/purescript-halogen-storybook/pull/5/commits/55f76c95c72e22b05a32e21b51e2da3833a792de

no need to add for now

**Comment by srghma** [comment]
actually they are needed

usecase https://github.com/bodil/purescript-smolder/blob/5548710e5467cf7b08d7def62c8fcf5ebfb6d9ae/src/Text/Smolder/Renderer/String.purs#L144
